# Generated by Django 4.1.7 on 2023-02-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_transections_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Image',
            field=models.ImageField(default='C:\\Users\\Admin\\OneDrive\\Desktop\\Online_Banking_System\\Online_Banking_System\\media\\default.jpg', upload_to='profile_images'),
        ),
    ]
